FROM microsoft/dotnet:2-sdk-jessie AS build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY . ./
WORKDIR /app/DDBMSP.Frontend.Web
RUN dotnet restore

# copy sources and build
RUN dotnet publish -c Release -o /app/out -r linux-x64
COPY DDBMSP.Silo/OrleansConfiguration.xml /app/out

# build runtime image
FROM microsoft/dotnet:2-runtime
WORKDIR /app
COPY --from=build-env /app/out ./

ENTRYPOINT ["dotnet", "DDBMSP.Frontend.Web.dll"]