version: '3.4'

services:

  consul:
    image: consul:latest
    command: agent -server -bootstrap -client=0.0.0.0 -bind=127.0.0.1
    networks:
      ddmsp-internal:
    ports:
      - "8500:8500"
    
  silo:
    image: silo
    build:
      context: .
      dockerfile: Dockerfile-Silo
    depends_on:
      - consul
      - storage
    networks:
      ddmsp-internal:
      
  storage:
    image: redis:alpine
    command: --save 300 1 --dbfilename dump.rdb --dir /data 
    volumes:
      - ../data:/data
    networks:
      ddmsp-internal:
    
  frontendweb:
    image: frontendweb
    build:
      context: .
      dockerfile: Dockerfile-Frontend-Web
    depends_on:
      - silo
    networks:
      ddmsp-internal:
    ports:
      - target: "5000"
        published: "8080"
        protocol: tcp
        mode: ingress
        
  cli:
      image: cli
      build:
        context: .
        dockerfile: Dockerfile-CLI
      depends_on:
        - silo
      networks:
        ddmsp-internal:
      volumes:
        - ../exportcli:/exportcli

networks:
  ddmsp-internal: